### PR TITLE
Support 0+ genes per variant, 0+ variants per gene

### LINKED ISSUE #114: Support 0+ genes per variant, 0+ variants per gene
When a merge happened to pull in the gene attribute to the genomicFeatures attribute, the gene was made manditory, while it was inteneded for the gene to remain optional. A gene OR variant should be manditory, which caters of CNV data. While Decipher has both SNV and CNV data, CNV data will not have an attached gene.

Merge commit in question which shows this: https://github.com/MatchmakerExchange/mme-apis/commit/064326aca62dbe59daa996befff9c8c6523b40d4

### PR DESCRIPTION
**Pull request by Relequestual**
Fixes #114 

I'm unsure of the "mandatory" and "optional" syntax we should use, but I have for now followed the same way it has been explained for Features. Alternativly, "one of" or some such. Open to suggestions / thoughts.

### CODE REVIEW

**Comment by fschiettecatte** [comment]
+1

**Comment by Relequestual** [comment]
Thanks @fschiettecatte - Sure @buske will +1 when he is not super busy (as I'm sure he is!) =]

**Comment by buske** [comment]
:) Sorry for the delay. I agree that `gene` should be optional if `variant` is provided. Are we sure we want to do the backwards-incompatible changing `gene` to the `genes` list? If I recall, this was to support single variants (e.g. CNVs) that overlap multiple genes.

**Comment by Relequestual** [comment]
Good spot. I think I'll make an additional commit which removes the change from `gene` to `genes`.

While it could be useful, I think without further discussion, it could actually provide a lot of false positives for Gemematcher. Thoughts @fschiettecatte ?

**Comment by fschiettecatte** [comment]
Probably, I will need to discuss with Nara as well.

**Comment by Relequestual** [comment]
No rush =]

**Comment by Relequestual** [comment]
@fschiettecatte Have you been able to discus this with Nara?

**Comment by fschiettecatte** [comment]
Not yet, she has been on call all last week so impossible to get hold of unless you have GBH, I am due to talk to her later today.

**Comment by fschiettecatte** [comment]
Talked to Nara, false positives are not an issue for us given the data we store.

**Comment by Relequestual** [comment]
Any push backs on this? If not, I'll merge for 1.1.

I'm presuiming we'll have a 1.1 before brand new shiny v2, whatever that ends up like.

**Comment by fschiettecatte** [comment]
No push back at this end.

**Comment by buske** [comment]
No push-back from me. I'm fine with breaking backwards-compatibility if others are. The next release will then be 2.0 if we want to abide by semantic versioning.

**Comment by antbro** [comment]
Seems sensible to me

Tony



________________________________

**Comment by Relequestual** [comment]
@buske I have to agree. There are a number of outstanding issues under pre 2.0.0-alpha milestones. I'll try to review them this week. I'll park this change for 2.0.0-alpha.

**Pull request closed without merging**
