### PR TITLE
Added AGHA MME disclaimer.

### PR DESCRIPTION
**Pull request by tudorgroza**

### CODE REVIEW

**Comment by Relequestual** [comment]
Hey @tudorgroza, Can you make this text or HTML please?
Thanks

**Comment by tudorgroza** [comment]
@Relequestual - done. Thanks.

**Comment by Relequestual** [comment]
Great. This is pretty similar to ours, and a good standard I expect.
Is it worth noting that this is colloquilly known as The Patient Archive?

**Comment by Relequestual** [comment]
Although we haven't discussed it, really love this new github functionality to review commits. I'm personally thinking I'll merge if someone else approves.

**Pull request merged**
