### PR TITLE
Issue #135: Distinguish patient-initatied match requests

### PR DESCRIPTION
**Pull request by buske**

### CODE REVIEW

**Comment by fschiettecatte** [comment]
My the GeneMatcher scheme the 'participant' is called 'patient', don't think this is an issue though, I can handle the mapping easily.

**Comment by buske** [comment]
@jxchong, what does MyGene2 use?

**Comment by jxchong** [comment]
Uh, I think we use "family" but it doesn't matter.

**Comment by Relequestual** [comment]
More importantly, does the description seem to fit for you guys?

**Comment by fschiettecatte** [comment]
We have three categories: 
- Researcher (MME -> researcher)
- Health Care Provider (MME -> clinical)
- Patient (MME -> participant)
@buske's categories fit nicely into those, and our users can select multiple categories, for example Nara is in researcher and clinical.

**Comment by fschiettecatte** [comment]
More details about 'Health Care Provider', we originally had 'clinician' but Nara felt that it was too restrictive and only included categories like 'doctor'/'physician' and not 'genetic counselor'. We wanted to make sure it included all categories that provided care in a clinical setting. 

Should we provide clarification as to which roles each category includes?

**Comment by Relequestual** [comment]
We should probably have clear definitions as to what we mean by each of these role terms... make sure we are all on the same page.

**Comment by jxchong** [comment]
That's funny. We went with clinician because Mike didn't like healthcare provider and because he thought clinician was more inclusive of genetic counselors.  Anyway we have the same three categories right now.

**Comment by buske** [comment]
Currently, we have the following:
* `clinician`: The contact person is a clinician responsible for the patient's care
* `researcher`: The contact person is a researcher with the necessary consent to submit the patient record
* `patient`: The contact person is the patient or a caregiver for the patient

Any changes anyone would like to include, or is this okay and clear enough for merge? @Relequestual

**Comment by Relequestual** [comment]
We don't actually store clinician or researcher, just clinician or lab scientist, but these are project roles, and sometimes in reality people are both. We must also consider that terms may mean different things in different countries or cultures.
I have a DECIPHER meeting shortly. I'll just check what people think if we have time.

**Comment by Relequestual** [comment]
Actually, I don't see any problems with this. Looks good by me

**Pull request merged**
