### PR TITLE
Issue #126: Backwards-compatible changes from develop branch

### PR DESCRIPTION
**Pull request by buske**
The following backwards-compatible changes were agreed to a while back and merged into the develop branch. I propose we add them to master for a 1.1 release of the API.

### CODE REVIEW

**Comment by Relequestual** [comment]
Moving forward to a 1.1 release! \o/

In a follow up to my previous comment, it wouldn't hurt if we create a release branch for the release, fix issues, then merge back into master and tag the release (a la gitflow). Tagging the release will generate a new DOI number FYI!

**Comment by fschiettecatte** [comment]
Fine with me.

**Comment by buske** [comment]
@Relequestual Sorry for straying from git flow. I've updated this PR (and others) to merge into a `release/v1.1` branch (based off of the old master, not develop). Once we release v1.1, we'll make a new develop from that and try to follow more carefully.

**Comment by Relequestual** [comment]
@buske It's not always easy to keep to unless you're doing it daily anyway. I personally do it with my personal project also, for sanity reasons.

Great! It can really pay off in some situations! =]

**Pull request merged**
